Added option to ignore value generators
Kros-sk/Kros.KORM pull request #100
Opened 2022-07-08 09:39 UTC by Peto-210

Added extension method that allows all operations within current transaction to ignore value generators

2022-07-11 13:15 UTC, satano requested changes

2022-07-12 10:11 UTC, Peto-210 commented on README.md
> +_dbSet.CommitChanges(ignoreValueGenerators = true);
Opravil som

2022-07-12 10:12 UTC, Peto-210 commented on src/Query/IDbSet.cs
> +        Task CommitChangesAsync(bool ignoreValueGenerators = false, CancellationToken cancellationToken = default);
Poradie parametrov som upravil a odstránil som zmenu v `IDatabaseExtensions.cs`

2022-07-13 07:11 UTC, satano approved these changes

2022-07-13 07:11 UTC, merged