Fix nullable types
Kros-sk/Kros.KORM pull request #79
Opened 2021-05-03 11:39 UTC by Burgyn

V prípade `record` typov bol problém pokiaľ tento typ obsahoval nullable hodnoty.

```csharp
public record Foo(int? NullableParameter)
```

Viac príkladov je v [repe od](https://github.com/rudolfficek/Korm.Query.Tests) @futudea. 

Všetky jeho príklady už prechádzajú až na jeden. Prípad, ktorý popisuje test `HaveDataWithNullColumnCorrectlyMapped_MappedAsRecordMutable` je aktuálne zámerne nepodporovaný.

--- 

Oprava bola realizovaná tak, že v prípade, že sa jedná o nullable typ tak sa na získanie hodnoty z `IDataReader` použije naša extension metóda (prislúchajúca k danému dátovému typu)

2021-05-03 16:05 UTC, satano requested changes

2021-05-03 16:05 UTC, satano commented on src/Materializer/ILGeneratorHelper.cs
> +            bool asVirtual = true)
Tento parameter podľa mňa nie je potrebný. či je metóda virtuálna vieš: `methodInfo.IsVirtual`.

2021-05-04 05:14 UTC, Burgyn commented on tests/Kros.KORM.UnitTests/Data/DataReaderExtensionsShould.cs
> +        public void GetNullableDecimal(double? value)
No podľa mňa nemôže, respektíve neviem ako to priamo zapísať. Pretože keď použiješ atribút `[InlineData]` tak tam priradzuješ hodnoty do parametra `object`. Pokiaľ zapíšeš desatinné číslo, napr.: `0.45` tak je automaticky `double`. V .NETe nie je priamá konverzia medzi `double` a nullable `decimal` (ja potrebujem nullable aby som tam mohol zadať aj `null` hodnotu). Pri typoch ako `float`, ... je možné použiť pretypovanie `[InlineData((float?)0.45)]`. Pri `decimal` však dostaneš kompilačnú chybu `Error	CS0182	An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type...`.

2021-05-04 07:12 UTC, satano approved these changes

2021-05-04 07:14 UTC, merged