Reserved words as names for columns or table
Kros-sk/Kros.KORM pull request #82
Opened 2021-06-01 16:31 UTC by Burgyn

If you need to name your column or table with a name that the server has among the reserved words (for example, `Order`), you must ensure that these names are quoted in queries.
If the queries are generated by KORM, then you must explicitly specify quotas in the `DatabaseConfiguration`.

```csharp
public class DatabaseConfiguration : DatabaseConfigurationBase
{
    public override void OnModelCreating(ModelConfigurationBuilder modelBuilder)
    {
        modelBuilder.QuoteTableAndColumns(Quota.SquareBrackets);
    }
}
```

> This cannot be set as the default due to backward compatibility.

2021-06-03 06:01 UTC, satano requested changes

2021-06-03 06:08 UTC, satano commented
Je to fajn tak ako je to spravené teraz, lebo je to jednoduché a funkčné. Ideálne by však bolo:

- Default je to zapnuté a dá sa to vypnúť.
- Typ "zátvoriek" je napevno daný podľa SQL providera, tzn. nemôžem si dať vlastný (nemám prečo). _Aj keď toto trochu naráža na to, že SQL Server umožňuje okrem hranatých zátvoriek používať aj úvodzovky (`"`), ak to človek chce a má zapnuté._

2021-06-09 04:12 UTC, Burgyn commented on src/Metadata/Quota.cs
> +    public class Quota
V princípe už sa v knižniciach snažím dávať triedy ako `internal`, ale tak ako je to teraz implementované musí byť `public`. Pretože to ňou človek konfiguruje.

Každopádne, idem sa pozrieť či je možné spraviť to čo píšeš nižšie, ak áno tak potom aj túto triedu spravím `internal`.

2021-06-09 05:13 UTC, Burgyn commented
> Je to fajn tak ako je to spravené teraz, lebo je to jednoduché a funkčné. Ideálne by však bolo:
> 
> * Default je to zapnuté a dá sa to vypnúť.
> * Typ "zátvoriek" je napevno daný podľa SQL providera, tzn. nemôžem si dať vlastný (nemám prečo). _Aj keď toto trochu naráža na to, že SQL Server umožňuje okrem hranatých zátvoriek používať aj úvodzovky (`"`), ak to človek chce a má zapnuté._

Snažil som sa to tak spraviť. Už som mal aj rozpracované, že to bolo zavesené čisto na `DefaultQuerySqlGenerator` (pretože ten má každý provider  vlastný). Ale potrebujem to aj v `SelectExpression` a `TableExpression` kam to neviem nejak jednoducho / elegantne pretlačiť z providera /query generátora.

Takže zatiaľ toto nechávam tak 😌

2021-06-14 05:59 UTC, satano approved these changes

2021-06-14 14:25 UTC, merged