Added execute with temp table extension for IDatabase.
Kros-sk/Kros.KORM pull request #84
Opened 2021-06-21 12:58 UTC by misho048

Added execute with temp table extension for IDatabase.
#81 issue resolved

2021-06-22 06:19 UTC, JardoHornak commented on src/IDatabaseExtensions.TempTable.cs
> +    public partial class IDatabaseExtensions
What will these extension methods do, if connected database is not SQL server database?

2021-06-22 10:49 UTC, Burgyn requested changes
Treba počúvnuť `update-docs` bota a dpolniť info do readme. Taktiež vyriešiť issue z CodeFactor bota.

2021-06-22 11:00 UTC, Burgyn requested changes

2021-06-22 11:00 UTC, Burgyn commented on src/IDatabaseExtensions.TempTable.cs
> +            => $"#tt_{Guid.NewGuid().ToString().Replace("-", "")}";
Miesto replace zavolať `ToString` so správnym parametrom.
`Guid.NewGuid().ToString("N")`

2021-06-23 04:14 UTC, Burgyn requested changes

2021-06-23 04:14 UTC, Burgyn commented on README.md
> +database.ExecuteWithTempTable<TValue>(IEnumerable<TValue> values, action);
Pridaj tu prosím nejaký príklad použitia, nech ten čo to ide použiť tuší ako to má použiť. Ja by som nevedel.

2021-06-23 07:39 UTC, Burgyn requested changes

2021-06-23 07:39 UTC, Burgyn commented on README.md
> +//for example: new List<int>(){0,1,2,3}
```suggestion
var ids = new List<int>(){ 0, 1, 2, 3 };
```

2021-06-23 07:39 UTC, Burgyn commented on README.md
> +_database.ExecuteWithTempTable(Ids, (database, tableName)
```suggestion
_database.ExecuteWithTempTable(ids, (database, tableName)
```

2021-06-23 07:39 UTC, Burgyn commented on README.md
> +//Ids is collection of Person ids.
Remove this comment

2021-06-23 07:54 UTC, Burgyn approved these changes

2021-06-23 07:55 UTC, merged